# Generated by Django 4.1.1 on 2022-09-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_file_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
